import tkinter as tk
from tkinter import messagebox, filedialog
import subprocess
import os
import shutil
import time

def select_export_folder():
    folder_selected = filedialog.askdirectory()
    if folder_selected:
        export_folder_var.set(folder_selected)

def select_reimport_folder():
    folder_selected = filedialog.askdirectory()
    if folder_selected:
        reimport_folder_var.set(folder_selected)

def run_export_scripts():
    export_folder = export_folder_var.get()
    
    if not export_folder:
        messagebox.showerror("Error", "Please select an export folder.")
        return

    uber_file = None

    # Find the .uber file in the export folder
    for file in os.listdir(export_folder):
        if file.endswith('.uber'):
            uber_file = file

    # Check if the .uber file is found
    if not uber_file:
        messagebox.showerror("Error", "No .uber file found in the export folder.")
        return

    try:
        # Get the current directory where the GUI script is located
        script_dir = os.path.dirname(os.path.abspath(__file__))
        
        # Paths to the extract scripts
        uber_extract_script = os.path.join(script_dir, 'modules/uber-extract.py')
        wiimusyx_extract_script = os.path.join(script_dir, 'modules/wiimusyx-extract.py')
        
        # Copy the scripts to the export folder
        shutil.copy(uber_extract_script, export_folder)
        shutil.copy(wiimusyx_extract_script, export_folder)
        
        # Change the working directory to the export folder
        os.chdir(export_folder)
        
        # Run uber-extract.py
        subprocess.run(['py', 'uber-extract.py', uber_file], check=True)
        messagebox.showinfo("Success", f"Successfully ran uber-extract.py on {uber_file}")
        
        # Wait for 3 seconds
        time.sleep(3)

        # Find the .sdir file generated by uber-extract.py
        sdir_file = None
        for file in os.listdir(export_folder):
            if file.endswith('.sdir'):
                sdir_file = file

        # Check if the .sdir file is found
        if not sdir_file:
            messagebox.showerror("Error", "No .sdir file generated by uber-extract.py.")
            return
        
        # Run wiimusyx-extract.py
        subprocess.run(['py', 'wiimusyx-extract.py', sdir_file], check=True)
        messagebox.showinfo("Success", f"Successfully ran wiimusyx-extract.py on {sdir_file}")
    except subprocess.CalledProcessError as e:
        messagebox.showerror("Error", f"Error running script: {e}")
    finally:
        # Change back to the original working directory
        os.chdir(original_cwd)
        
        # Remove the copied scripts from the export folder
        try:
            os.remove(os.path.join(export_folder, 'uber-extract.py'))
            os.remove(os.path.join(export_folder, 'wiimusyx-extract.py'))
        except OSError as e:
            messagebox.showerror("Error", f"Error deleting script: {e}")

def find_uber_and_samp_files(export_folder):
    uber_file_path = None
    samp_file_path = None

    for file in os.listdir(export_folder):
        if file.endswith('.uber'):
            uber_file_path = os.path.join(export_folder, file)
        elif file.endswith('.samp'):
            samp_file_path = os.path.join(export_folder, file)

    return uber_file_path, samp_file_path

def reimport_dsp_and_samp_files():
    export_folder = export_folder_var.get()
    reimport_folder = reimport_folder_var.get()
    
    if not export_folder or not reimport_folder:
        messagebox.showerror("Error", "Please select both export and reimport folders.")
        return

    export_dsp_files = [file for file in os.listdir(export_folder) if file.endswith('.dsp')]
    reimport_dsp_files = [file for file in os.listdir(reimport_folder) if file.endswith('.dsp')]

    uber_file_path, samp_file_path = find_uber_and_samp_files(export_folder)

    if not uber_file_path:
        messagebox.showerror("Error", "No .uber file found in the export folder.")
        return

    if not samp_file_path:
        messagebox.showerror("Error", "No .samp file found in the export folder.")
        return

    for dsp_file in export_dsp_files:
        if dsp_file in reimport_dsp_files:
            # Paths for export and reimport DSP files
            export_dsp_path = os.path.join(export_folder, dsp_file)
            reimport_dsp_path = os.path.join(reimport_folder, dsp_file)

            # Read data from export DSP file for Uber replacement
            with open(export_dsp_path, 'rb') as export_f:
                export_uber_data = export_f.read()[0x1C:0x20]

            # Read data from reimport DSP file for Uber replacement
            with open(reimport_dsp_path, 'rb') as reimport_f:
                reimport_uber_data = reimport_f.read()[0x1C:0x20]

            # Find and replace data in Uber file
            with open(uber_file_path, 'r+b') as uber_f:
                uber_data = uber_f.read()
                offset = uber_data.find(export_uber_data)
                if offset != -1:
                    uber_f.seek(offset)
                    uber_f.write(reimport_uber_data)

            # Read data from export DSP file for SAMP replacement
            with open(export_dsp_path, 'rb') as export_f:
                exported_data = export_f.read()[0x60:]

            # Read data from reimport DSP file for SAMP replacement
            with open(reimport_dsp_path, 'rb') as reimport_f:
                reimported_data = reimport_f.read()[0x60:]

                # Pad with zeros if reimported data is shorter
                if len(reimported_data) < len(exported_data):
                    reimported_data += b'\x00' * (len(exported_data) - len(reimported_data))

            # Find and replace data in SAMP file
            with open(samp_file_path, 'r+b') as samp_f:
                samp_data = samp_f.read()
                offset = samp_data.find(exported_data)
                if offset != -1:
                    samp_f.seek(offset)
                    samp_f.write(reimported_data)

            status_text.insert(tk.END, f"{dsp_file} reimport: Success!\n")
        else:
            status_text.insert(tk.END, f"{dsp_file} reimport: No matching file found in reimport folder.\n")
        status_text.see(tk.END)  # Scroll to the end

    status_text.insert(tk.END, "Reimport process completed.\n")
    status_text.see(tk.END)  # Scroll to the end

    status_text.insert(tk.END, "Reimport process completed.\n")
    status_text.see(tk.END)  # Scroll to the end

original_cwd = os.getcwd()
# Create the main window
root = tk.Tk()
root.title("Unleashed Sound Manager")
root.geometry("700x400")  # Set the window size

# Create StringVars to hold the export and reimport folder paths
export_folder_var = tk.StringVar()
reimport_folder_var = tk.StringVar()

# Create and place the folder selection components for export folder
export_folder_label = tk.Label(root, text="Select Export Folder:")
export_folder_label.grid(row=0, column=0, padx=10, pady=10, sticky="w")

export_folder_entry = tk.Entry(root, textvariable=export_folder_var, width=50)
export_folder_entry.grid(row=0, column=1, padx=10, pady=10)

export_browse_button = tk.Button(root, text="Browse", command=select_export_folder)
export_browse_button.grid(row=0, column=2, padx=10, pady=10)

# Create and place the folder selection components for reimport folder
reimport_folder_label = tk.Label(root, text="Select Reimport Folder:")
reimport_folder_label.grid(row=1, column=0, padx=10, pady=10, sticky="w")

reimport_folder_entry = tk.Entry(root, textvariable=reimport_folder_var, width=50)
reimport_folder_entry.grid(row=1, column=1, padx=10, pady=10)

reimport_browse_button = tk.Button(root, text="Browse", command=select_reimport_folder)
reimport_browse_button.grid(row=1, column=2, padx=10, pady=10)

# Create and place the "Export Now" button
export_button = tk.Button(root, text="Export Now!", command=run_export_scripts)
export_button.grid(row=2, column=1, columnspan=4, pady=20)
# Create and place the "Reimport Now" button
reimport_button = tk.Button(root, text="Reimport Now!", command=reimport_dsp_and_samp_files)
reimport_button.grid(row=2, column=0, columnspan=2, pady=20)

# Create and place the status text widget
status_text = tk.Text(root, width=80, height=10)
status_text.grid(row=3, column=0, columnspan=3, padx=10, pady=10)

# Create and place the developer information text
developer_label = tk.Label(root, text="Developer: 龍崎 晶 (Digitzaki)", anchor="w", width=25)
developer_label.grid(row=4, column=0, padx=20, pady=(0, 20), sticky="w")

# Create and place the build information text
build_label = tk.Label(root, text="Build: 1.1 (6162024)", anchor="w", width=20)
build_label.grid(row=4, column=2, padx=10, pady=(0, 10), sticky="w")

# Run the application
root.mainloop()